version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Python AI Service
  - package-ecosystem: "pip"
    directory: "/SmartQuitIoT-AI"
    schedule:
      interval: "weekly"
    groups:
       python-dependencies:
          patterns:
            - "*"

  # Java Backend Service
  - package-ecosystem: "maven"
    directory: "/SmartQuitIoT-BE"
    schedule:
      interval: "weekly"
    groups:
       spring-dependencies:
          patterns:
            - "*"
